#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_DIR="$ROOT_DIR/Axis/Configuration"
SECRETS_FILE="$SECRETS_DIR/Secrets.swift"
API_KEY="${ANTHROPIC_API_KEY:-}"

mkdir -p "$SECRETS_DIR"

cat > "$SECRETS_FILE" <<EOF
import Foundation

// Generated by scripts/generate_secrets.sh — do not commit.
enum Secrets {
    static let anthropicAPIKey = "$API_KEY"
}
EOF

echo "[secrets] Wrote $SECRETS_FILE"
